#!/bin/bash

set -e
set -x

status-set maintenance "Installing dependencies"
apt-get update -yy && apt-get upgrade -yy
apt-get install -yy python3-flask gunicorn3 git wget

mkdir -p /srv/http
cd /srv/http

if [ -d /srv/http/hello-juju ]
then
    status-set maintenance "Updating source code"
    cd hello-juju
    git pull
else
    status-set maintenance "Downloading hello-juju source"
    git clone https://github.com/juju/hello-juju
fi

status-set waiting "waiting for start hook"